name: CodeQL

on:
  push:
    branches: [dev, master]
  pull_request:
    branches: [dev]

jobs:
  analyze:
    runs-on: [ubuntu-latest]

steps:
- name: Checkout repository
  uses: actions/checkout@v4

# Initializes CodeQL tools and creates a codebase for analysis.
- name: Initialize CodeQL
  uses: github/codeql-action/init@v3
  with:
    languages: ['c-cpp', 'actions']

- name: Build C and C++ code
  run: |
    cmake -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc
    cmake --build build


